[package]
name = "vista-ingestion"
version = "0.1.0"
edition = "2021"

[dependencies]
vista-core = { path = "../vista-core" }
solana-client = "1.16.0"
solana-sdk = "1.16.0"
tokio = { version = "1.29.1", features = ["full"] }
async-trait = "0.1.71"